version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - printf '[{"name":"converter-service","imageUri":"246368831125.dkr.ecr.us-east-1.amazonaws.com/converter-service:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - target/converter-1.0.jar
